spring:
  # Database Settings
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL Driver
    url: jdbc:mysql://cobell-mysql.cqrboqcusntt.ap-northeast-2.rds.amazonaws.com:3306/Cobell?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: cobell123

  # JPA Settings
  jpa:
    showSql: true # 실행한 SQL을 보여줌
    hibernate:
      ddlAuto: none # DDL(create/update/create-drop/validate/none)
    properties:
      hibernate:
        globally_quoted_identifiers: true # query의 식별자(테이블명, 필드명 등)을 `로 감싸줌
#        format_sql: true # SQL을 보기 좋게 formatting 해줌
#        generate_statistics: true # 쿼리 수행 통계를 확인할 수 있다.
  # 파일 용량 설정
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 110MB

# Spring Boot Application 실행시 콘솔에 뜨는 로그
# logging.level.org.hibernate=debug

# Entity 필드명과 DB 컬럼명 사이의 이름 변환 규칙
# spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# 이미지 외부 경로
custom:
  path:
#    uploadImage: '/Users/hyunji/Documents/Cobell/resources/'
    uploadImage: '/home/ec2-user/resources/'

